"""Add poll close

Revision ID: 851d754cc113
Revises: 3cac60383864
Create Date: 2024-08-27 11:23:06.106674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851d754cc113'
down_revision: Union[str, None] = '3cac60383864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_poll', sa.Column('block_answer_delta_hours', sa.Integer(), server_default='24', nullable=False, comment='через сколько часов после публикации блокировать ответы'))
    op.add_column('table_poll', sa.Column('is_poll_is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='статус блокировки опроса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_poll', 'is_poll_is_blocked')
    op.drop_column('table_poll', 'block_answer_delta_hours')
    # ### end Alembic commands ###
