"""Add Chat, Poll

Revision ID: 3cac60383864
Revises:
Create Date: 2024-07-31 00:28:17.547252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cac60383864'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_chat',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('chat_id', sa.String(length=128), nullable=False, comment='id чата/группы Telegram'),
        sa.Column('is_group', sa.Boolean(), nullable=False, comment='статус группового чата'),
        sa.Column('title', sa.String(length=64), nullable=False, comment='название чата'),
        sa.PrimaryKeyConstraint('id'),
        comment='Чат',
    )
    op.create_table(
        'table_poll',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('chat_id', sa.String(length=128), nullable=False, comment='id чата/группы Telegram'),
        sa.Column('dates_skip', postgresql.ARRAY(sa.String(length=10)), server_default=sa.text("'{}'::text[]"), nullable=True, comment='даты для пропуска отправки'),
        sa.Column('is_allows_anonymous_answers', sa.Boolean(), nullable=False, comment='статус анонимных ответов'),
        sa.Column('is_allows_multiple_answers', sa.Boolean(), nullable=False, comment='статус множественного выбора ответов'),
        sa.Column('last_send_date', sa.Date(), nullable=True, comment='дата последней отправки опроса'),
        sa.Column('message_id', sa.String(length=128), nullable=True, comment='id сообщения Telegram'),
        sa.Column('topic', sa.String(length=100), nullable=False, comment='тема опроса'),
        sa.Column('options', postgresql.ARRAY(sa.String(length=100)), nullable=False, comment='варианты ответов'),
        sa.Column('send_days_of_week_list', postgresql.ARRAY(sa.String(length=3)), nullable=False, comment='дни недели для отправки'),
        sa.Column('send_time', sa.Time(), nullable=False, comment='время для отправки'),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='id пользователя Telegram, кто отправил опрос'),
        sa.PrimaryKeyConstraint('id'),
        comment='Опрос',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_poll')
    op.drop_table('table_chat')
    # ### end Alembic commands ###
