"""Add Course and User

Revision ID: e7f65985f860
Revises: 851d754cc113
Create Date: 2025-04-29 12:08:22.187492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e7f65985f860'
down_revision: Union[str, None] = '851d754cc113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_course',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('description', sa.String(length=900), nullable=False, comment='описание курса'),
        sa.Column('keyboard_coordinates', sa.String(length=5), nullable=False, comment='координаты на клавиатуре'),
        sa.Column('picture_file_id', sa.String(length=256), nullable=False, comment='id картинки в Telegram'),
        sa.Column('tariffs', sa.String(length=1000), nullable=False, comment='тарифы'),
        sa.Column('title', sa.String(length=48), nullable=False, comment='название'),
        sa.Column('user_id_telegram', sa.Integer(), nullable=False, comment='id пользователя Telegram, кто добавил курс'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('keyboard_coordinates'),
        sa.UniqueConstraint('title'),
        comment='Курс',
    )
    op.create_table(
        'table_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('datetime_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата и время старта бота'),
        sa.Column('datetime_stop', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True, comment='дата и время остановки бота'),
        sa.Column('id_telegram', sa.String(length=17), nullable=False, comment='id в Telegram'),
        sa.Column('is_stopped_bot', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='статус остановки бота'),
        sa.Column('message_main_last_id', sa.Integer(), server_default=sa.text('NULL'), nullable=True, comment='id последнего сообщения "Главная"'),
        sa.Column('name_first', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='имя'),
        sa.Column('name_last', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='фамилия'),
        sa.Column('username', sa.String(length=32), server_default=sa.text('NULL'), nullable=True, comment='username в Telegram'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_telegram'),
        comment='Пользователь',
    )
    op.create_unique_constraint('table_chat_chat_id_unique_constraint', 'table_chat', ['chat_id'])
    op.alter_column('table_poll', 'is_poll_is_blocked', new_column_name='is_blocked')
    op.alter_column('table_poll', 'user_id', new_column_name='user_id_telegram')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_poll', 'user_id_telegram', new_column_name='user_id')
    op.alter_column('table_poll', 'is_blocked', new_column_name='is_poll_is_blocked')
    op.drop_constraint('table_chat_chat_id_unique_constraint', 'table_chat', type_='unique')
    op.drop_table('table_user')
    op.drop_table('table_course')
    # ### end Alembic commands ###
